spring:
  datasource:
    url: jdbc:mysql://localhost:3306/transaction_management_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  batch:
    jdbc:
      initialize-schema: always
server:
  port: 9090